# fly.toml app configuration file generated for space-saver on 2023-09-07T15:45:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "space-saver"
primary_region = "sea"

[build]

[env]
  REACT_APP_API_URL="https://space-saver-backend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
