# fly.toml app configuration file generated for space-saver-backend on 2023-09-07T16:13:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "space-saver-backend"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
